name: Tests, Docs, Deploy

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:

  # Test Docs
  test-docs:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install sphinx
        python -m pip install alabaster
        python -m pip install sphinx-reredirects

    - name: Test Docs
      run: sphinx-build -W --keep-going doc _build/html


  # Save Artifacts
  create-save-artifacts:
    runs-on: ubuntu-24.04
    needs: [test-docs]
    permissions:
      contents: write

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install sphinx
        python -m pip install alabaster
        python -m pip install sphinx-reredirects

    - name: Create artifacts
      run: |
        mkdir dist
        sphinx-build -W --keep-going doc _build/html

    - name: Save artifacts to Github Actions
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: _build/html/*
        if-no-files-found: error
